version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=${TZ:-GMT}
      - PLEX_CLAIM=${PLEX_CLAIM:-CHANGE_ME}
    network_mode: host
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ./media:/media